import { describe, expect, it } from 'vitest';
import { addColumn, applyCommands, cloneSchema, diffSchemas, emptySchema, generateCreateSql, generateStatements, getDialect, type Schema } from '../src';

function erd(): Schema {
  return applyCommands(emptySchema(), [
    { op: 'createTable', name: 'member', logicalName: '회원', columns: [
      { name: 'member_id', logicalName: '회원번호', type: 'BIGINT', primaryKey: true, autoIncrement: true },
      { name: 'email', logicalName: '이메일', type: 'VARCHAR(100)', nullable: false, unique: true },
      { name: 'is_active', type: 'BOOLEAN', nullable: false, default: 'TRUE' },
      { name: 'grade', type: 'VARCHAR(10)', nullable: false, default: "'BASIC'" },
      { name: 'created_at', type: 'DATETIME', nullable: false, default: 'CURRENT_TIMESTAMP' },
    ] },
    { op: 'createTable', name: 'orders', logicalName: '주문', columns: [
      { name: 'order_id', type: 'BIGINT', primaryKey: true, autoIncrement: true },
      { name: 'amount', type: 'DECIMAL(12,2)', nullable: false, default: '0' },
      { name: 'memo', type: 'TEXT' },
    ] },
    { op: 'addRelation', parent: 'member', child: 'orders', onDelete: 'CASCADE', onUpdate: 'CASCADE' },
    { op: 'addIndex', table: 'orders', columns: ['member_id', 'amount'], name: 'ix_orders_member_amount' },
  ]).schema;
}

describe('MariaDB', () => {
  it('MySQL과 같은 문법으로 만든다', () => {
    expect(generateCreateSql(erd(), getDialect('mariadb'))).toBe(generateCreateSql(erd(), getDialect('mysql')));
  });
  it('MariaDB가 돌려주는 기본값 표기를 같은 것으로 본다', () => {
    const d = getDialect('mariadb');
    expect(d.normalizeDefault('current_timestamp()')).toBe(d.normalizeDefault('CURRENT_TIMESTAMP'));
    expect(d.normalizeDefault("'BASIC'")).toBe("'BASIC'");
    expect(d.normalizeDefault('NULL')).toBeNull();
  });
});

describe('Oracle', () => {
  const d = getDialect('oracle');
  it('CREATE: VARCHAR2·NUMBER·CLOB·TIMESTAMP, IDENTITY, 기본값 순서, 코멘트, FK는 ON DELETE만', () => {
    const sql = generateCreateSql(erd(), d);
    expect(sql).toContain('member_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(sql).toContain('email VARCHAR2(100) NOT NULL');
    expect(sql).toContain('is_active NUMBER(1) DEFAULT 1 NOT NULL');
    expect(sql).toContain("grade VARCHAR2(10) DEFAULT 'BASIC' NOT NULL");
    expect(sql).toContain('created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL');
    expect(sql).toContain('amount NUMBER(12,2) DEFAULT 0 NOT NULL');
    expect(sql).toContain('memo CLOB');
    expect(sql).toContain('CONSTRAINT pk_member PRIMARY KEY (member_id)');
    expect(sql).toContain("COMMENT ON TABLE member IS '회원'");
    expect(sql).toContain("COMMENT ON COLUMN member.email IS '이메일'");
    expect(sql).toContain('FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE;');
    expect(sql).not.toContain('ON UPDATE');
    // 문장 끝에 세미콜론을 붙이지 않는다 (드라이버로 실행)
    expect(generateStatements(diffSchemas(emptySchema(), erd(), d), d).every((s) => !s.sql.trimEnd().endsWith(';') || s.sql.startsWith('BEGIN'))).toBe(true);
  });

  it('예약어·camelCase 이름은 따옴표, 평범한 이름은 그대로', () => {
    expect(d.quote('member')).toBe('member');
    expect(d.quote('MEMBER')).toBe('MEMBER');
    expect(d.quote('createdAt')).toBe('"createdAt"');
    expect(d.quote('comment')).toBe('"comment"');
    expect(d.quote('user')).toBe('"user"');
  });

  it('ALTER: MODIFY에는 바뀐 것만, 이름 변경은 RENAME COLUMN, 기존 컬럼 IDENTITY 추가는 이유를 담은 오류', () => {
    const base = erd();
    const next = cloneSchema(base);
    const member = next.tables[0];
    member.columns[1].length = '200';
    member.columns[3].defaultValue = "'GOLD'";
    member.columns[4].nullable = true;
    member.columns[2].name = 'active_yn';
    addColumn(next, member.id, { name: 'phone', type: 'VARCHAR', length: '20', logicalName: '전화' });
    next.tables[1].columns[1].autoIncrement = true;
    const sql = generateStatements(diffSchemas(base, next, d), d).map((s) => s.sql);
    expect(sql).toContain('ALTER TABLE member MODIFY (email VARCHAR2(200))');
    expect(sql).toContain("ALTER TABLE member MODIFY (grade DEFAULT 'GOLD')");
    expect(sql).toContain('ALTER TABLE member MODIFY (created_at NULL)');
    expect(sql).toContain('ALTER TABLE member RENAME COLUMN is_active TO active_yn');
    expect(sql).toContain('ALTER TABLE member ADD (phone VARCHAR2(20))');
    expect(sql).toContain("COMMENT ON COLUMN member.phone IS '전화'");
    expect(sql.some((s) => s.startsWith('BEGIN RAISE_APPLICATION_ERROR(-20001') && s.includes('orders.amount'))).toBe(true);
  });

  it('ON UPDATE는 비교하지 않고, RESTRICT는 NO ACTION과 같다', () => {
    const base = erd();
    const next = cloneSchema(base);
    next.relations[0].onUpdate = 'NO ACTION';
    expect(diffSchemas(base, next, d).changes).toEqual([]);
    expect(d.normalizeAction('RESTRICT')).toBe('NO ACTION');
    expect(d.normalizeDefault('SYSTIMESTAMP')).toBe('CURRENT_TIMESTAMP');
    expect(d.normalizeDefault("'BASIC' \n")).toBe("'BASIC'");
  });
});

describe('SQL Server', () => {
  const d = getDialect('mssql');
  it('CREATE: [이름], IDENTITY, BIT·DATETIME2·NVARCHAR(MAX), 설명은 MS_Description, FK ON DELETE/UPDATE', () => {
    const sql = generateCreateSql(erd(), d);
    expect(sql).toContain('[member_id] BIGINT IDENTITY(1,1) NOT NULL');
    expect(sql).toContain('[is_active] BIT NOT NULL DEFAULT 1');
    expect(sql).toContain('[created_at] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP');
    expect(sql).toContain('[memo] NVARCHAR(MAX) NULL');
    expect(sql).toContain('CONSTRAINT [PK_member] PRIMARY KEY ([member_id])');
    expect(sql).toContain("@value = N'회원', @level0type = N'SCHEMA', @level0name = @s, @level1type = N'TABLE', @level1name = N'member'");
    expect(sql).toContain("@level2type = N'COLUMN', @level2name = N'email'");
    expect(sql).toContain('REFERENCES [member] ([member_id]) ON DELETE CASCADE ON UPDATE CASCADE');
    expect(sql).toContain('CREATE UNIQUE INDEX [ux_member_email] ON [member] ([email])');
  });

  it('ALTER: 이름은 sp_rename, 기본값은 기존 제약조건을 찾아 지우고 다시, 컬럼 삭제 전에도 기본값 제거', () => {
    const base = erd();
    const next = cloneSchema(base);
    next.tables[0].columns[3].defaultValue = "'GOLD'";
    next.tables[0].columns[2].name = 'active_yn';
    next.tables[1].columns.splice(1, 1); // amount 삭제 (기본값 있음)
    next.tables[1].indexes = [];
    const sql = generateStatements(diffSchemas(base, next, d), d).map((s) => s.sql);
    expect(sql).toContain("EXEC sp_rename N'[member].[is_active]', N'active_yn', N'COLUMN'");
    const df = sql.findIndex((s) => s.includes('sys.default_constraints') && s.includes("c.name = N'grade'"));
    expect(df).toBeGreaterThan(-1);
    expect(sql[df + 1]).toBe("ALTER TABLE [member] ADD DEFAULT 'GOLD' FOR [grade]");
    const dropDf = sql.findIndex((s) => s.includes('sys.default_constraints') && s.includes("c.name = N'amount'"));
    expect(sql[dropDf + 1]).toBe('ALTER TABLE [orders] DROP COLUMN [amount]');
  });

  it('인덱스가 걸린 컬럼의 타입을 바꾸면 그 인덱스를 잠깐 지웠다 다시 만든다', () => {
    const base = erd();
    const next = cloneSchema(base);
    next.tables[0].columns[1].length = '200'; // email (UNIQUE)
    const sql = generateStatements(diffSchemas(base, next, d), d).map((s) => s.sql);
    expect(sql).toEqual([
      'DROP INDEX [ux_member_email] ON [member]',
      'ALTER TABLE [member] ALTER COLUMN [email] VARCHAR(200) NOT NULL',
      'CREATE UNIQUE INDEX [ux_member_email] ON [member] ([email])',
    ]);
  });

  it('SQL Server가 괄호로 감싼 기본값을 같은 것으로 본다', () => {
    expect(d.normalizeDefault("('BASIC')")).toBe("'BASIC'");
    expect(d.normalizeDefault('((0))')).toBe('0');
    expect(d.normalizeDefault('(getdate())')).toBe('CURRENT_TIMESTAMP');
    expect(d.normalizeDefault("(N'가')")).toBe("'가'");
    expect(d.normalizeDefault("('(a)')")).toBe("'(a)'");
  });
});

describe('모든 DB 공통', () => {
  it.each(['mysql', 'mariadb', 'postgresql', 'oracle', 'mssql'] as const)('%s: 같은 ERD끼리는 바뀐 것이 없고, 타입 표시가 비교에 안정적이다', (id) => {
    const d = getDialect(id);
    const s = erd();
    expect(diffSchemas(s, cloneSchema(s), d).changes).toEqual([]);
    for (const t of erd().tables) for (const c of t.columns) expect(d.renderType(c)).toBe(d.renderType({ ...c }));
    expect(generateCreateSql(erd(), d).length).toBeGreaterThan(100);
  });
});
