import { describe, expect, it } from 'vitest';
import { alignToCurrent, applyChanges, diffIncoming, generateCreateSql, generateMigration, getDialect, parseDdl } from '../src';

const MYSQL_DDL = `
-- 회원
CREATE TABLE IF NOT EXISTS \`member\` (
  \`member_id\` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '회원번호',
  \`email\` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '이메일',
  \`is_active\` tinyint(1) NOT NULL DEFAULT '1',
  \`point\` int(11) DEFAULT NULL,
  \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`member_id\`),
  UNIQUE KEY \`uk_member_email\` (\`email\`),
  KEY \`ix_member_created\` (\`created_at\`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='회원';

CREATE TABLE orders (
  order_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(12, 2) UNSIGNED NOT NULL DEFAULT 0.00,
  memo TEXT,
  CONSTRAINT fk_orders_member FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE
);
INSERT INTO member VALUES (1);
`;

const PG_DDL = `
CREATE TABLE public.category (
  category_id serial PRIMARY KEY,
  name character varying(50) NOT NULL UNIQUE,
  parent_id integer REFERENCES category,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  tags text[],
  status varchar(10) DEFAULT 'A'::character varying NOT NULL
);
CREATE TABLE product (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY,
  category_id integer NOT NULL,
  price numeric(10,2) DEFAULT 0 NOT NULL,
  CONSTRAINT product_pk PRIMARY KEY (product_id)
);
ALTER TABLE ONLY product ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(category_id);
CREATE INDEX ix_product_category ON public.product USING btree (category_id);
COMMENT ON TABLE category IS '분류';
COMMENT ON COLUMN public.category.name IS '분류명';
`;

describe('DDL 가져오기', () => {
  it('MySQL', () => {
    const { schema, dialect, warnings } = parseDdl(MYSQL_DDL);
    expect(dialect).toBe('mysql');
    expect(warnings).toHaveLength(1); // INSERT
    const member = schema.tables[0];
    expect(member.name).toBe('member');
    expect(member.logicalName).toBe('회원');
    const [id, email, active, point, created] = member.columns;
    expect(id).toMatchObject({ type: 'BIGINT UNSIGNED', primaryKey: true, autoIncrement: true, logicalName: '회원번호', nullable: false });
    expect(email).toMatchObject({ type: 'VARCHAR', length: '100', nullable: false });
    expect(active).toMatchObject({ type: 'BOOLEAN', defaultValue: "'1'" });
    expect(point).toMatchObject({ type: 'INT', length: '', nullable: true, defaultValue: null });
    expect(created.defaultValue).toBe('CURRENT_TIMESTAMP');
    expect(member.indexes.map((i) => [i.name, i.unique])).toEqual([['uk_member_email', true], ['ix_member_created', false]]);

    const orders = schema.tables[1];
    expect(orders.columns[2]).toMatchObject({ type: 'DECIMAL UNSIGNED', length: '12,2', defaultValue: '0.00' });
    expect(schema.relations).toHaveLength(1);
    expect(schema.relations[0]).toMatchObject({ name: 'fk_orders_member', onDelete: 'CASCADE', cardinality: '1:N' });
  });

  it('PostgreSQL', () => {
    const { schema, dialect, warnings } = parseDdl(PG_DDL);
    expect(dialect).toBe('postgresql');
    expect(warnings).toEqual([]);
    const [category, product] = schema.tables;
    expect(category.logicalName).toBe('분류');
    expect(category.columns[0]).toMatchObject({ type: 'INT', autoIncrement: true, primaryKey: true });
    expect(category.columns[1]).toMatchObject({ type: 'VARCHAR', length: '50', unique: true, logicalName: '분류명' });
    expect(category.columns[3]).toMatchObject({ type: 'TIMESTAMPTZ', defaultValue: 'now()', nullable: false });
    expect(category.columns[4].type).toBe('TEXT[]');
    expect(category.columns[5].defaultValue).toBe("'A'::character varying");
    expect(product.primaryKeyName).toBe('product_pk');
    expect(product.columns[0]).toMatchObject({ autoIncrement: true, primaryKey: true });
    expect(product.indexes[0].name).toBe('ix_product_category');
    // 자기 참조 + ALTER TABLE로 추가한 FK
    expect(schema.relations.map((r) => r.name)).toEqual(['', 'fk_product_category']);
  });

  it('가져온 스키마로 만든 SQL을 다시 읽으면 변경이 없다 (왕복)', () => {
    for (const ddl of [MYSQL_DDL, PG_DDL]) {
      const first = parseDdl(ddl);
      const dialect = getDialect(first.dialect);
      const sql = generateCreateSql(first.schema, dialect);
      const second = parseDdl(sql, { dialect: first.dialect });
      expect(second.warnings).toEqual([]);
      const diff = diffIncoming(first.schema, second.schema, dialect);
      expect(diff.changes.map((c) => c.summary)).toEqual([]);
    }
  });
});

describe('들어온 스키마 맞추기 / 반영', () => {
  it('DB에서 컬럼이 추가·변경되면 그 부분만 ERD에 반영하고 위치와 논리명은 유지한다', () => {
    const erd = parseDdl(MYSQL_DDL).schema;
    erd.tables[0].position = { x: 100, y: 200 };
    erd.tables[1].logicalName = '주문';

    const db = parseDdl(
      MYSQL_DDL.replace('memo TEXT,', 'memo VARCHAR(500),\n  status VARCHAR(20) NOT NULL,').replace("COMMENT='회원'", ''),
    ).schema;
    const dialect = getDialect('mysql');
    const diff = diffIncoming(erd, db, dialect);
    // DB에 코멘트가 없어도 ERD의 논리명은 지우지 않는다
    expect(diff.changes.map((c) => c.summary)).toEqual([
      'orders.memo 변경: 타입 TEXT → VARCHAR(500)',
      'orders.status 컬럼 추가',
    ]);

    // 컬럼 추가만 골라 반영
    const selected = new Set(diff.changes.filter((c) => c.kind === 'addColumn').map((c) => c.id));
    const next = applyChanges(erd, diff, selected);
    expect(next.tables[0].position).toEqual({ x: 100, y: 200 });
    expect(next.tables[0].logicalName).toBe('회원');
    expect(next.tables[1].logicalName).toBe('주문');
    expect(next.tables[1].columns.map((c) => c.name)).toEqual(['order_id', 'member_id', 'amount', 'memo', 'status']);
    expect(next.tables[1].columns[3].type).toBe('TEXT');
    // 반영 후 다시 비교하면 고르지 않은 변경만 남는다
    expect(diffIncoming(next, db, dialect).changes.map((c) => c.kind)).toEqual(['alterColumn']);
    expect(diffIncoming(applyChanges(erd, diff), db, dialect).changes).toEqual([]);
  });

  it('ERD를 DB에 적용할 때 바뀐 테이블만 건드린다', () => {
    const db = parseDdl(MYSQL_DDL).schema;
    const erd = parseDdl(MYSQL_DDL).schema; // 다른 id로 읽힌 같은 스키마
    erd.tables[1].columns.push({ ...erd.tables[1].columns[3], id: 'new', name: 'coupon_code', type: 'VARCHAR', length: '30' });
    erd.tables[1].indexes.push({ id: 'ix', name: '', columnIds: ['new'], unique: true });
    const dialect = getDialect('mysql');
    const { statements } = generateMigration(alignToCurrent(db, erd), erd, dialect);
    expect(statements.map((s) => s.sql)).toEqual([
      'ALTER TABLE `orders` ADD COLUMN `coupon_code` VARCHAR(30) NULL AFTER `memo`',
      'CREATE UNIQUE INDEX `ux_orders_coupon_code` ON `orders` (`coupon_code`)',
    ]);
  });
});


describe('합치기용 DDL', () => {
  it('DDL에 없는 테이블을 참조하는 FK는 기존 스키마에서 찾는다', () => {
    const current = parseDdl('CREATE TABLE member (member_id BIGINT PRIMARY KEY);').schema;
    const ddl = 'CREATE TABLE coupon (id BIGINT PRIMARY KEY, member_id BIGINT, FOREIGN KEY (member_id) REFERENCES member (member_id));';
    expect(parseDdl(ddl).warnings).toHaveLength(1);
    const { schema, warnings } = parseDdl(ddl, { context: current });
    expect(warnings).toEqual([]);
    const diff = diffIncoming(current, schema, getDialect('mysql'));
    expect(diff.changes.map((c) => c.summary)).toEqual(['coupon 테이블 생성', 'coupon → member 외래키 추가']);
  });
});
