import { describe, expect, it } from 'vitest';
import {
  cloneSchema,
  createColumn,
  createIndex,
  createRelation,
  createTable,
  diffSchemas,
  generateCreateSql,
  generateMigration,
  getDialect,
  toScript,
  type Schema,
} from '../src';

function sample(): Schema {
  const memberId = createColumn({ id: 'm_id', name: 'member_id', logicalName: '회원번호', type: 'BIGINT', length: '', primaryKey: true, nullable: false, autoIncrement: true });
  const email = createColumn({ id: 'm_email', name: 'email', logicalName: '이메일', type: 'VARCHAR', length: '100', nullable: false, unique: true });
  const member = createTable({ id: 't_member', name: 'member', logicalName: '회원', columns: [memberId, email] });

  const orderId = createColumn({ id: 'o_id', name: 'order_id', type: 'BIGINT', length: '', primaryKey: true, nullable: false, autoIncrement: true });
  const orderMember = createColumn({ id: 'o_member', name: 'member_id', type: 'BIGINT', length: '', nullable: false });
  const status = createColumn({ id: 'o_status', name: 'status', type: 'VARCHAR', length: '20', nullable: false, defaultValue: "'READY'" });
  const orders = createTable({
    id: 't_orders', name: 'orders', logicalName: '주문', columns: [orderId, orderMember, status],
    indexes: [createIndex({ id: 'i_status', name: 'ix_orders_status', columnIds: ['o_status'] })],
  });

  const fk = createRelation({ id: 'r1', fromTableId: 't_orders', fromColumnIds: ['o_member'], toTableId: 't_member', toColumnIds: ['m_id'], onDelete: 'CASCADE' });
  return { tables: [member, orders], relations: [fk] };
}

describe('전체 CREATE', () => {
  it('MySQL', () => {
    const sql = generateCreateSql(sample(), getDialect('mysql'));
    expect(sql).toContain("CREATE TABLE `member` (\n  `member_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원번호'");
    expect(sql).toContain('PRIMARY KEY (`member_id`)');
    expect(sql).toContain("COMMENT='회원'");
    expect(sql).toContain('CREATE UNIQUE INDEX `ux_member_email` ON `member` (`email`)');
    expect(sql).toContain('CREATE INDEX `ix_orders_status` ON `orders` (`status`)');
    expect(sql).toContain('ALTER TABLE `orders` ADD CONSTRAINT `fk_orders_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE CASCADE');
    // FK는 테이블 생성 뒤에 온다
    expect(sql.indexOf('ADD CONSTRAINT')).toBeGreaterThan(sql.lastIndexOf('CREATE TABLE'));
  });

  it('PostgreSQL', () => {
    const sql = generateCreateSql(sample(), getDialect('postgresql'));
    expect(sql).toContain('member_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(sql).toContain('CONSTRAINT member_pkey PRIMARY KEY (member_id)');
    expect(sql).toContain("COMMENT ON TABLE member IS '회원'");
    expect(sql).toContain("COMMENT ON COLUMN member.member_id IS '회원번호'");
    expect(sql).toContain("status VARCHAR(20) NOT NULL DEFAULT 'READY'");
  });
});

describe('변경분 (ALTER)', () => {
  it('변경이 없으면 아무것도 만들지 않는다', () => {
    const { statements } = generateMigration(sample(), sample(), getDialect('mysql'));
    expect(statements).toEqual([]);
  });

  it('바뀐 테이블만 ALTER하고 새 테이블은 CREATE로 분류한다', () => {
    const base = sample();
    const target = cloneSchema(base);
    const orders = target.tables[1];
    orders.columns[2].name = 'order_status'; // 이름 변경
    orders.columns[2].length = '30';
    orders.columns.push(createColumn({ id: 'o_memo', name: 'memo', type: 'TEXT', length: '' }));
    orders.indexes.push(createIndex({ id: 'i_member', columnIds: ['o_member'] }));
    target.tables.push(createTable({ id: 't_coupon', name: 'coupon', columns: [createColumn({ id: 'c_id', name: 'coupon_id', type: 'BIGINT', length: '', primaryKey: true, nullable: false })] }));

    const { statements } = generateMigration(base, target, getDialect('mysql'));
    const sqls = statements.map((s) => s.sql);

    expect(statements.some((s) => s.tableName === 'member')).toBe(false);
    expect(sqls).toContain("ALTER TABLE `orders` CHANGE COLUMN `status` `order_status` VARCHAR(30) NOT NULL DEFAULT 'READY'");
    expect(sqls).toContain('ALTER TABLE `orders` ADD COLUMN `memo` TEXT NULL AFTER `order_status`');
    expect(sqls).toContain('CREATE INDEX `ix_orders_member_id` ON `orders` (`member_id`)');
    const create = statements.filter((s) => s.category === 'create');
    expect(create.map((s) => s.tableName)).toEqual(['coupon']);
    expect(statements.filter((s) => s.category === 'alter').every((s) => s.tableName === 'orders')).toBe(true);
  });

  it('PostgreSQL 컬럼 변경은 필요한 부분만 바꾼다', () => {
    const base = sample();
    const target = cloneSchema(base);
    const status = target.tables[1].columns[2];
    status.nullable = true;
    status.defaultValue = null;
    status.logicalName = '주문상태';
    const { statements } = generateMigration(base, target, getDialect('postgresql'));
    expect(statements.map((s) => s.sql)).toEqual([
      'ALTER TABLE orders ALTER COLUMN status DROP NOT NULL, ALTER COLUMN status DROP DEFAULT',
      "COMMENT ON COLUMN orders.status IS '주문상태'",
    ]);
  });

  it('테이블 삭제는 FK를 먼저 지우고 DROP으로 분류하며 경고를 단다', () => {
    const base = sample();
    const target = cloneSchema(base);
    target.tables = target.tables.filter((t) => t.id !== 't_orders');
    target.relations = [];
    const { statements } = generateMigration(base, target, getDialect('mysql'));
    expect(statements.map((s) => [s.category, s.sql])).toEqual([
      ['drop', 'ALTER TABLE `orders` DROP FOREIGN KEY `fk_orders_member`'],
      ['drop', 'DROP TABLE `orders`'],
    ]);
    const script = toScript(statements);
    expect(script).toContain('-- 주의: 테이블과 모든 데이터가 삭제됩니다');
  });

  it('선택한 변경만 SQL로 만든다', () => {
    const base = sample();
    const target = cloneSchema(base);
    target.tables[0].columns.push(createColumn({ id: 'm_name', name: 'name' }));
    target.tables[1].columns.push(createColumn({ id: 'o_memo', name: 'memo' }));
    const diff = diffSchemas(base, target, getDialect('mysql'));
    const memberChange = diff.changes.find((c) => c.tableName === 'member')!;
    const { statements } = generateMigration(base, target, getDialect('mysql'), new Set([memberChange.id]));
    expect(statements).toHaveLength(1);
    expect(statements[0].tableName).toBe('member');
  });

  it('기본키와 타입 별칭은 같은 의미면 변경으로 보지 않는다', () => {
    const base = sample();
    const target = cloneSchema(base);
    target.tables[0].columns[0].nullable = true; // PK는 항상 NOT NULL
    target.tables[1].columns[2].defaultValue = "'READY'";
    const pgBase = cloneSchema(base);
    // 숫자 기본값은 값으로 비교 (0.00 = 0)
    pgBase.tables[1].columns.push({ ...pgBase.tables[1].columns[2], id: 'o_amount', name: 'amount', type: 'DECIMAL', length: '12,2', defaultValue: '0.00' });
    target.tables[1].columns.push({ ...target.tables[1].columns[2], id: 'o_amount', name: 'amount', type: 'NUMERIC', length: '12,2', defaultValue: '0' });
    pgBase.tables[1].columns[0].type = 'INT8';
    target.tables[1].columns[0].type = 'BIGINT';
    expect(generateMigration(pgBase, target, getDialect('postgresql')).statements).toEqual([]);
  });
});
