import { indexName, primaryKeyColumns, relationName, type Column, type Table } from '../model';
import { quoteExpression, columnNames, literal, normalizeDefaultCommon, relationTables, sqlComment, typeWithLength, indexKeys } from './common';
import type { Dialect } from './types';

// Oracle 12c 이상 (IDENTITY 컬럼). 따옴표 없는 이름은 Oracle이 대문자로 바꿔 저장하므로,
// 소문자·대문자로만 된 이름은 따옴표 없이 쓰고 DB에서 읽을 때 소문자로 돌려 ERD 이름과 맞춘다.

const TYPE_MAP: Record<string, string> = {
  VARCHAR: 'VARCHAR2',
  'CHARACTER VARYING': 'VARCHAR2',
  NVARCHAR: 'NVARCHAR2',
  TEXT: 'CLOB',
  TINYTEXT: 'CLOB',
  MEDIUMTEXT: 'CLOB',
  LONGTEXT: 'CLOB',
  JSON: 'CLOB',
  JSONB: 'CLOB',
  BIGINT: 'NUMBER(19)',
  INT8: 'NUMBER(19)',
  BIGSERIAL: 'NUMBER(19)',
  INT: 'NUMBER(10)',
  INTEGER: 'NUMBER(10)',
  INT4: 'NUMBER(10)',
  SERIAL: 'NUMBER(10)',
  MEDIUMINT: 'NUMBER(10)',
  SMALLINT: 'NUMBER(5)',
  INT2: 'NUMBER(5)',
  TINYINT: 'NUMBER(3)',
  BOOLEAN: 'NUMBER(1)',
  BOOL: 'NUMBER(1)',
  BIT: 'NUMBER(1)',
  DECIMAL: 'NUMBER',
  NUMERIC: 'NUMBER',
  DOUBLE: 'BINARY_DOUBLE',
  'DOUBLE PRECISION': 'BINARY_DOUBLE',
  FLOAT: 'BINARY_FLOAT',
  REAL: 'BINARY_FLOAT',
  DATETIME: 'TIMESTAMP',
  TIME: 'TIMESTAMP',
  TIMESTAMPTZ: 'TIMESTAMP WITH TIME ZONE',
  BYTEA: 'BLOB',
  LONGBLOB: 'BLOB',
  VARBINARY: 'BLOB',
  UUID: 'VARCHAR2(36)',
};

/** 길이를 붙이지 않는 타입 */
const NO_LENGTH = new Set(['CLOB', 'NCLOB', 'BLOB', 'DATE', 'BINARY_DOUBLE', 'BINARY_FLOAT', 'TIMESTAMP', 'TIMESTAMP WITH TIME ZONE', 'LONG']);

const RESERVED = new Set(
  ('access add all alter and any as asc audit between by char check cluster column comment compress connect create current date decimal default delete desc ' +
    'distinct drop else exclusive exists file float for from grant group having identified immediate in increment index initial insert integer intersect into ' +
    'is level like lock long maxextents minus mlslabel mode modify noaudit nocompress not nowait null number of offline on online option or order pctfree prior ' +
    'public raw rename resource revoke row rowid rownum rows select session set share size smallint start successful synonym sysdate table then to trigger uid ' +
    'union unique update user validate values varchar varchar2 view whenever where with').split(' '),
);

/** 소문자만(또는 대문자만)으로 된 평범한 이름은 따옴표 없이, 그 외(camelCase, 예약어 등)는 따옴표로 정확히 */
function q(name: string): string {
  const simple = /^[A-Za-z][A-Za-z0-9_$#]*$/.test(name) && (name === name.toLowerCase() || name === name.toUpperCase()) && name.length <= 128;
  if (simple && !RESERVED.has(name.toLowerCase())) return name;
  return '"' + name.replace(/"/g, '""') + '"';
}

function renderType(column: Column): string {
  const raw = column.type.trim().toUpperCase().replace(/\s+(UNSIGNED|ZEROFILL)/g, '');
  const mapped = TYPE_MAP[raw] ?? raw;
  if (mapped.includes('(')) return mapped; // NUMBER(19) 등 정해진 크기
  if (NO_LENGTH.has(mapped)) return mapped;
  // 문자열은 길이가 꼭 있어야 한다
  const length = column.length || (/^N?VARCHAR2$/.test(mapped) ? '255' : '');
  return typeWithLength(mapped, length);
}

function defaultClause(column: Column): string {
  const v = column.defaultValue?.trim();
  if (!v || column.autoIncrement) return '';
  // TRUE/FALSE는 NUMBER(1)에 1/0으로
  if (/^true$/i.test(v)) return ' DEFAULT 1';
  if (/^false$/i.test(v)) return ' DEFAULT 0';
  return ` DEFAULT ${v}`;
}

function columnDefinition(column: Column): string {
  let def = `${q(column.name)} ${renderType(column)}`;
  const generated = column.generated?.expression.trim();
  if (generated) return `${def} GENERATED ALWAYS AS (${quoteExpression(generated, q)}) VIRTUAL${!column.nullable || column.primaryKey ? ' NOT NULL' : ''}`;
  if (column.autoIncrement) def += ' GENERATED BY DEFAULT AS IDENTITY';
  def += defaultClause(column);
  if (!column.nullable || column.primaryKey) def += ' NOT NULL';
  return def;
}

const comment = (target: string, item: { comment: string; logicalName: string }) => `COMMENT ON ${target} IS ${literal(sqlComment(item))}`;
const tableComment = (table: Table) => comment(`TABLE ${q(table.name)}`, table);
const columnComment = (table: Table, column: Column) => comment(`COLUMN ${q(table.name)}.${q(column.name)}`, column);
const pkName = (table: Table) => table.primaryKeyName || `pk_${table.name}`.slice(0, 128);
/** 한 번에 바꿀 수 없는 변경은 이유를 담은 오류로 멈춘다 (조용히 다른 일을 하지 않게) */
const fail = (message: string) => `BEGIN RAISE_APPLICATION_ERROR(-20001, ${literal(message)}); END;`;

export const oracle: Dialect = {
  id: 'oracle',
  label: 'Oracle',
  typeSuggestions: ['NUMBER', 'BIGINT', 'INT', 'VARCHAR2', 'NVARCHAR2', 'CHAR', 'CLOB', 'DATE', 'TIMESTAMP', 'BLOB', 'BINARY_DOUBLE', 'BOOLEAN'],
  supportsOnUpdate: false,

  quote: q,
  renderType,
  // Oracle FK는 ON DELETE CASCADE / SET NULL만 있다
  normalizeAction: (action) => (action === 'CASCADE' || action === 'SET NULL' ? action : 'NO ACTION'),
  normalizeDefault(value) {
    if (value === null) return null;
    const v = normalizeDefaultCommon(value.trim());
    if (v === 'SYSTIMESTAMP' || v === 'CURRENT_TIMESTAMP') return 'CURRENT_TIMESTAMP';
    if (v === 'TRUE') return '1';
    if (v === 'FALSE') return '0';
    return v;
  },

  createTable(table) {
    const lines = table.columns.map((c) => '  ' + columnDefinition(c));
    const pk = primaryKeyColumns(table);
    if (pk.length) lines.push(`  CONSTRAINT ${q(pkName(table))} PRIMARY KEY (${pk.map((c) => q(c.name)).join(', ')})`);
    const statements = [`CREATE TABLE ${q(table.name)} (\n${lines.join(',\n')}\n)`];
    if (sqlComment(table)) statements.push(tableComment(table));
    for (const c of table.columns) if (sqlComment(c)) statements.push(columnComment(table, c));
    return statements;
  },
  dropTable: (table) => [`DROP TABLE ${q(table.name)}`],
  renameTable: (from, to) => [`ALTER TABLE ${q(from.name)} RENAME TO ${q(to.name)}`],
  setTableComment: (table) => [tableComment(table)],

  addColumn(table, column) {
    const statements = [`ALTER TABLE ${q(table.name)} ADD (${columnDefinition(column)})`];
    if (sqlComment(column)) statements.push(columnComment(table, column));
    return statements;
  },
  dropColumn: (table, column) => [`ALTER TABLE ${q(table.name)} DROP COLUMN ${q(column.name)}`],
  alterColumn(table, before, after, changed) {
    const t = q(table.name);
    const statements: string[] = [];
    if (changed.includes('name')) statements.push(`ALTER TABLE ${t} RENAME COLUMN ${q(before.name)} TO ${q(after.name)}`);
    if (changed.includes('autoIncrement')) {
      statements.push(
        after.autoIncrement
          ? fail(`Oracle은 기존 컬럼을 IDENTITY로 바꿀 수 없습니다: ${table.name}.${after.name} (새 컬럼을 만들어 옮기세요)`)
          : `ALTER TABLE ${t} MODIFY (${q(after.name)} DROP IDENTITY)`,
      );
    }
    // MODIFY에는 바뀐 것만 넣는다 (이미 NOT NULL인데 NOT NULL을 또 쓰면 오류)
    const parts: string[] = [];
    if (changed.includes('type')) parts.push(renderType(after));
    if (changed.includes('defaultValue') && !after.autoIncrement) parts.push(defaultClause(after).trim() || 'DEFAULT NULL');
    if (changed.includes('nullable')) parts.push(after.nullable && !after.primaryKey && !after.autoIncrement ? 'NULL' : 'NOT NULL');
    if (parts.length) statements.push(`ALTER TABLE ${t} MODIFY (${q(after.name)} ${parts.join(' ')})`);
    if (changed.includes('comment')) statements.push(columnComment(table, after));
    return statements;
  },
  changePrimaryKey(before, after) {
    const statements: string[] = [];
    if (primaryKeyColumns(before).length) statements.push(`ALTER TABLE ${q(after.name)} DROP PRIMARY KEY`);
    const newPk = primaryKeyColumns(after);
    if (newPk.length) statements.push(`ALTER TABLE ${q(after.name)} ADD CONSTRAINT ${q(`pk_${after.name}`)} PRIMARY KEY (${newPk.map((c) => q(c.name)).join(', ')})`);
    return statements;
  },

  indexSupport: { expression: true },
  generatedSupport: { virtual: true },
  createIndex(table, index) {
    return [`CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${q(indexName(table, index))} ON ${q(table.name)} (${indexKeys(table, index, q)})`];
  },
  dropIndex: (table, index) =>
    index.isConstraint ? [`ALTER TABLE ${q(table.name)} DROP CONSTRAINT ${q(indexName(table, index))}`] : [`DROP INDEX ${q(indexName(table, index))}`],

  addForeignKey(schema, relation) {
    const { from, to } = relationTables(schema, relation);
    const fromCols = columnNames(from, relation.fromColumnIds).map(q).join(', ');
    const toCols = columnNames(to, relation.toColumnIds).map(q).join(', ');
    let sql = `ALTER TABLE ${q(from.name)} ADD CONSTRAINT ${q(relationName(schema, relation))} FOREIGN KEY (${fromCols}) REFERENCES ${q(to.name)} (${toCols})`;
    if (relation.onDelete === 'CASCADE' || relation.onDelete === 'SET NULL') sql += ` ON DELETE ${relation.onDelete}`;
    return [sql];
  },
  dropForeignKey(schema, relation) {
    const { from } = relationTables(schema, relation);
    return [`ALTER TABLE ${q(from.name)} DROP CONSTRAINT ${q(relationName(schema, relation))}`];
  },
};
