import { indexName, primaryKeyColumns, relationName, type Column, type Table } from '../model';
import { columnNames, literal, normalizeDefaultCommon, relationTables, sqlComment, typeWithLength } from './common';
import type { Dialect } from './types';

const TYPE_MAP: Record<string, string> = {
  DATETIME: 'TIMESTAMP',
  TINYINT: 'SMALLINT',
  MEDIUMINT: 'INTEGER',
  INT: 'INTEGER',
  DOUBLE: 'DOUBLE PRECISION',
  FLOAT: 'REAL',
  BLOB: 'BYTEA',
  LONGBLOB: 'BYTEA',
  MEDIUMTEXT: 'TEXT',
  LONGTEXT: 'TEXT',
  TINYTEXT: 'TEXT',
  BOOL: 'BOOLEAN',
  DECIMAL: 'NUMERIC',
  'CHARACTER VARYING': 'VARCHAR',
  CHARACTER: 'CHAR',
  'TIMESTAMP WITHOUT TIME ZONE': 'TIMESTAMP',
  'TIMESTAMP WITH TIME ZONE': 'TIMESTAMPTZ',
  SERIAL: 'INTEGER',
  BIGSERIAL: 'BIGINT',
  INT4: 'INTEGER',
  INT8: 'BIGINT',
  INT2: 'SMALLINT',
};

/** 길이를 붙이지 않는 타입 (MySQL에서 가져온 INT(11) 같은 표시 폭 제거) */
const NO_LENGTH = new Set([
  'INTEGER', 'BIGINT', 'SMALLINT', 'BOOLEAN', 'TEXT', 'BYTEA', 'DATE', 'REAL',
  'DOUBLE PRECISION', 'JSON', 'JSONB', 'UUID',
]);

const RESERVED = new Set([
  'all', 'and', 'any', 'array', 'as', 'asc', 'case', 'check', 'column', 'constraint', 'create',
  'default', 'desc', 'distinct', 'do', 'else', 'end', 'for', 'foreign', 'from', 'grant', 'group',
  'having', 'in', 'into', 'is', 'join', 'key', 'limit', 'not', 'null', 'offset', 'on', 'or',
  'order', 'primary', 'references', 'select', 'table', 'then', 'to', 'union', 'unique', 'user',
  'using', 'when', 'where', 'with',
]);

function q(name: string): string {
  if (/^[a-z_][a-z0-9_]*$/.test(name) && !RESERVED.has(name)) return name;
  return '"' + name.replace(/"/g, '""') + '"';
}

function renderType(column: Column): string {
  const raw = column.type.trim().toUpperCase();
  const type = TYPE_MAP[raw] ?? raw;
  const length = NO_LENGTH.has(type) ? '' : column.length;
  return typeWithLength(type, length);
}

function columnDefinition(column: Column): string {
  const parts = [q(column.name), renderType(column)];
  if (column.autoIncrement) parts.push('GENERATED BY DEFAULT AS IDENTITY');
  if (!column.nullable || column.primaryKey) parts.push('NOT NULL');
  if (column.defaultValue !== null && column.defaultValue.trim() !== '' && !column.autoIncrement) {
    parts.push(`DEFAULT ${column.defaultValue.trim()}`);
  }
  return parts.join(' ');
}

function columnComment(table: Table, column: Column): string {
  const comment = sqlComment(column);
  return `COMMENT ON COLUMN ${q(table.name)}.${q(column.name)} IS ${comment ? literal(comment) : 'NULL'}`;
}

function tableComment(table: Table): string {
  const comment = sqlComment(table);
  return `COMMENT ON TABLE ${q(table.name)} IS ${comment ? literal(comment) : 'NULL'}`;
}

function pkName(table: Table): string {
  return table.primaryKeyName || `${table.name}_pkey`;
}

export const postgresql: Dialect = {
  id: 'postgresql',
  label: 'PostgreSQL',
  typeSuggestions: [
    'BIGINT', 'INTEGER', 'SMALLINT', 'NUMERIC', 'DOUBLE PRECISION', 'REAL', 'BOOLEAN',
    'VARCHAR', 'CHAR', 'TEXT', 'DATE', 'TIMESTAMP', 'TIMESTAMPTZ', 'TIME',
    'UUID', 'JSON', 'JSONB', 'BYTEA',
  ],

  quote: q,
  renderType,
  normalizeDefault(value) {
    if (value === null) return null;
    // 'Y'::character varying → 'Y'
    const stripped = value.replace(/::[a-z ]+(\[\])?$/i, '');
    const v = normalizeDefaultCommon(stripped);
    if (v === 'NOW()') return 'CURRENT_TIMESTAMP';
    return v;
  },

  createTable(table) {
    const lines = table.columns.map((c) => '  ' + columnDefinition(c));
    const pk = primaryKeyColumns(table);
    if (pk.length) lines.push(`  CONSTRAINT ${q(pkName(table))} PRIMARY KEY (${pk.map((c) => q(c.name)).join(', ')})`);
    const statements = [`CREATE TABLE ${q(table.name)} (\n${lines.join(',\n')}\n)`];
    if (sqlComment(table)) statements.push(tableComment(table));
    for (const c of table.columns) if (sqlComment(c)) statements.push(columnComment(table, c));
    return statements;
  },
  dropTable: (table) => [`DROP TABLE ${q(table.name)}`],
  renameTable: (from, to) => [`ALTER TABLE ${q(from.name)} RENAME TO ${q(to.name)}`],
  setTableComment: (table) => [tableComment(table)],

  addColumn(table, column) {
    const statements = [`ALTER TABLE ${q(table.name)} ADD COLUMN ${columnDefinition(column)}`];
    if (sqlComment(column)) statements.push(columnComment(table, column));
    return statements;
  },
  dropColumn: (table, column) => [`ALTER TABLE ${q(table.name)} DROP COLUMN ${q(column.name)}`],
  alterColumn(table, before, after, changed) {
    const t = q(table.name);
    const statements: string[] = [];
    if (changed.includes('name')) statements.push(`ALTER TABLE ${t} RENAME COLUMN ${q(before.name)} TO ${q(after.name)}`);
    const c = q(after.name);
    const actions: string[] = [];
    if (changed.includes('type')) {
      const type = renderType(after);
      actions.push(`ALTER COLUMN ${c} TYPE ${type} USING ${c}::${type}`);
    }
    if (changed.includes('autoIncrement')) {
      if (after.autoIncrement) {
        if (before.defaultValue) actions.push(`ALTER COLUMN ${c} DROP DEFAULT`);
        actions.push(`ALTER COLUMN ${c} ADD GENERATED BY DEFAULT AS IDENTITY`);
      } else {
        actions.push(`ALTER COLUMN ${c} DROP IDENTITY IF EXISTS`);
      }
    }
    if (changed.includes('nullable')) {
      actions.push(after.nullable && !after.primaryKey ? `ALTER COLUMN ${c} DROP NOT NULL` : `ALTER COLUMN ${c} SET NOT NULL`);
    }
    if (changed.includes('defaultValue') && !after.autoIncrement) {
      const v = after.defaultValue?.trim();
      actions.push(v ? `ALTER COLUMN ${c} SET DEFAULT ${v}` : `ALTER COLUMN ${c} DROP DEFAULT`);
    }
    if (actions.length) statements.push(`ALTER TABLE ${t} ${actions.join(', ')}`);
    if (changed.includes('comment')) statements.push(columnComment(table, after));
    return statements;
  },
  changePrimaryKey(before, after) {
    const newPk = primaryKeyColumns(after);
    const actions: string[] = [];
    if (primaryKeyColumns(before).length) actions.push(`DROP CONSTRAINT ${q(pkName(before))}`);
    if (newPk.length) actions.push(`ADD CONSTRAINT ${q(`${after.name}_pkey`)} PRIMARY KEY (${newPk.map((c) => q(c.name)).join(', ')})`);
    return actions.length ? [`ALTER TABLE ${q(after.name)} ${actions.join(', ')}`] : [];
  },

  createIndex(table, index) {
    const cols = columnNames(table, index.columnIds).map(q).join(', ');
    return [`CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${q(indexName(table, index))} ON ${q(table.name)} (${cols})`];
  },
  dropIndex: (table, index) => [`DROP INDEX ${q(indexName(table, index))}`],

  addForeignKey(schema, relation) {
    const { from, to } = relationTables(schema, relation);
    const fromCols = columnNames(from, relation.fromColumnIds).map(q).join(', ');
    const toCols = columnNames(to, relation.toColumnIds).map(q).join(', ');
    let sql = `ALTER TABLE ${q(from.name)} ADD CONSTRAINT ${q(relationName(schema, relation))} FOREIGN KEY (${fromCols}) REFERENCES ${q(to.name)} (${toCols})`;
    if (relation.onDelete !== 'NO ACTION') sql += ` ON DELETE ${relation.onDelete}`;
    if (relation.onUpdate !== 'NO ACTION') sql += ` ON UPDATE ${relation.onUpdate}`;
    return [sql];
  },
  dropForeignKey(schema, relation) {
    const { from } = relationTables(schema, relation);
    return [`ALTER TABLE ${q(from.name)} DROP CONSTRAINT ${q(relationName(schema, relation))}`];
  },
};
